import { auth } from "@clerk/nextjs/server";
import Link from "next/link";
import { readdirSync, readFileSync, existsSync } from "fs";
import { join } from "path";

interface ModuleInfo {
  slug: string;
  title: string;
  description?: string;
  order: number;
}

function getModules(): ModuleInfo[] {
  const contentDir = join(process.cwd(), "content");
  const dirs = readdirSync(contentDir, { withFileTypes: true }).filter((d) =>
    d.isDirectory(),
  );

  const modules: ModuleInfo[] = [];
  for (const dir of dirs) {
    const jsonPath = join(contentDir, dir.name, "module.json");
    if (!existsSync(jsonPath)) continue;
    const data = JSON.parse(readFileSync(jsonPath, "utf-8"));
    modules.push({
      slug: dir.name,
      title: data.title ?? dir.name,
      description: data.description,
      order: typeof data.order === "number" ? data.order : Number.MAX_SAFE_INTEGER,
    });
  }
  modules.sort((a, b) => a.order - b.order);
  return modules;
}

export default async function HomePage({
  searchParams,
}: {
  searchParams: Promise<{ sort?: string }>;
}) {
  const { userId } = await auth();
  const { sort } = await searchParams;
  const ascending = sort !== "desc";
  const allModules = getModules();
  if (!ascending) allModules.reverse();

  return (
    <div>
      {/* Hero */}
      <div className="mb-10">
        <h1 className="mb-3 text-3xl font-bold tracking-tight text-sand-900">
          Respiratory Therapy Course
        </h1>
        <p className="text-lg text-sand-600">
          Study modules, quizzes, and resources for your coursework.
        </p>
      </div>

      {/* AI disclaimer */}
      <div className="mb-3 flex items-start gap-3 rounded-2xl border border-clay-200 bg-clay-100/40 px-5 py-4">
        <div className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-clay-500/10 text-clay-600">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>
        </div>
        <p className="text-sm text-sand-700">
          <strong>AI-Generated Content Warning:</strong> The content, quizzes, and audio on this site are generated by AI and may contain errors or inaccuracies. Always cross-reference with your official lesson slides and course materials. Use the feedback button to report any issues or concerns.
        </p>
      </div>

      {/* Login prompt for quizzes */}
      <div className="mb-6 flex items-start gap-3 rounded-2xl border border-sky-100 bg-sky-100/50 px-5 py-4">
        <div className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-sky-500/10 text-sky-600">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4"/><polyline points="10 17 15 12 10 7"/><line x1="15" y1="12" x2="3" y2="12"/></svg>
        </div>
        <p className="text-sm text-sand-700">
          <strong>Login Required for Quizzes:</strong> You must be signed in to take quizzes and track your progress. Click the <strong>Sign in</strong> button above or use the link on any quiz tab to get started.
        </p>
      </div>

      {/* Sign in prompt */}
      {!userId && (
        <div className="mb-8 flex items-center gap-3 rounded-2xl border border-sky-100 bg-sky-100/50 px-5 py-4">
          <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-sky-500/10 text-sky-600">
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4" /><polyline points="10 17 15 12 10 7" /><line x1="15" y1="12" x2="3" y2="12" /></svg>
          </div>
          <p className="text-sm text-sand-700">
            <Link href="/sign-in" className="font-semibold text-sky-600 underline decoration-sky-300 underline-offset-2 transition hover:text-sky-700">
              Sign in
            </Link>{" "}
            to track your progress and take quizzes.
          </p>
        </div>
      )}

      {/* Sort toggle */}
      <div className="mb-4 flex items-center justify-end">
        <Link
          href={ascending ? "/?sort=desc" : "/"}
          className="flex items-center gap-1.5 rounded-xl border border-sand-200 bg-white px-3 py-1.5 text-xs font-medium text-sand-600 transition-all hover:border-sand-300 hover:text-sand-800"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="14"
            height="14"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            className={ascending ? "rotate-180" : ""}
          >
            <path d="m3 8 4-4 4 4" />
            <path d="M7 4v16" />
            <path d="M11 12h4" />
            <path d="M11 16h7" />
            <path d="M11 20h10" />
          </svg>
          {ascending ? "Oldest first" : "Newest first"}
        </Link>
      </div>

      {/* Module cards */}
      <div className="space-y-3">
        {allModules.map((mod) => (
          <Link
            key={mod.slug}
            href={`/modules/${mod.slug}`}
            className="group flex items-center gap-4 rounded-2xl border border-sand-200 bg-white p-5 transition-all hover:border-sand-300 hover:shadow-sm"
          >
            <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-sand-100 text-sm font-bold text-sand-500 transition-colors group-hover:bg-sand-200 group-hover:text-sand-700">
              {String(mod.order).padStart(2, "0")}
            </div>
            <div className="min-w-0 flex-1">
              <p className="font-medium text-sand-900 transition-colors group-hover:text-terracotta-600">
                {mod.title}
              </p>
              {mod.description && (
                <p className="mt-0.5 line-clamp-1 text-sm text-sand-500">
                  {mod.description}
                </p>
              )}
            </div>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="shrink-0 text-sand-300 transition-colors group-hover:text-sand-500"><polyline points="9 18 15 12 9 6" /></svg>
          </Link>
        ))}

        {allModules.length === 0 && (
          <div className="rounded-2xl border border-dashed border-sand-300 p-8 text-center text-sand-500">
            No modules yet. Run{" "}
            <code className="rounded bg-sand-100 px-2 py-0.5 text-xs font-medium text-sand-700">
              npm run db:seed
            </code>{" "}
            to get started.
          </div>
        )}
      </div>
    </div>
  );
}
